### PR TITLE
Go snmp server#20

### LINKED ISSUE #20: Use mainline `gosnmp` to allow for up-to-date crypto functions
Mirror of gosnmp/gosnmp#446 to coordinate changes to GoSNMPServer

### PR DESCRIPTION
**Pull request by upsampled**
Fixed #20 working with `gosnmp/gosnmp` mainline

Also works with SHA256/AES256, to test this:

* ensure you have compiled net-snmp to support more advanced hash/cipher
```sh
$snmpwalk -h 2>&1 | grep "\-x\|\-a"
  -a PROTOCOL           set authentication protocol (MD5|SHA|SHA-224|SHA-256|SHA-384|SHA-512)
  -x PROTOCOL           set privacy protocol (DES|AES|AES-192|AES-256)
```
* modify `gosnmpserver/main.go` and run it:
```go
AuthenticationProtocol:   gosnmp.SHA256,
PrivacyProtocol:          gosnmp.AES256,
```
* access the server with:
```sh
$snmpwalk -v 3 -l authPriv -n public -u testuser -a SHA-256 -A testauth -x AES-256 -X testpriv-L e 127.0.0.1:1161 1
```

### CODE REVIEW

**Comment by slayercat** [comment]
sure~

**Comment by slayercat** [comment]
I am doing some tests and found that both the `TestServerTestsSuite/TestGetSetOids/SNMPWalk` and `TestServerTestsSuite/TestGetSetOids/SNMPSet` tests have failed. I am still investigating the reasons for these failures.

**Comment by upsampled** [comment]
I had some time this morning to look into this, below is a stand alone program that runs the server for the test. Here is what I found:

### `TestServerTestsSuite/TestGetSetOids/SNMPWalk`

When I run `snmpwalk -v2c -c public localhost:6161 1` I get the following:

```
$ snmpwalk -v2c -c public localhost:6161 1
iso.2.3.1 = INTEGER: 0
iso.2.3.2 = NULL
iso.2.3.3 = ""
iso.2.3.4 = OID: iso.2.3.4
iso.2.3.6 = Counter32: 0
iso.2.3.7 = Gauge32: 0
iso.2.3.8 = Timeticks: (0) 0:00:00.00
iso.2.3.9 = Counter64: 0
iso.2.3.10 = 0
Timeout: No Response from localhost:6161
```
So the issue is serving Oids `iso.2.3.11` and `iso.2.3.12`. This is probably another issue with Oid sorting and lookup (IE: https://github.com/slayercat/GoSNMPServer/commit/f220d18995267b7e1ad44a23fb1239e6741eeaa1). I'll look into it more later.


### `TestServerTestsSuite/TestGetSetOids/SNMPSet/ByGoSNMP/Counter32`, 
it is pretty straight forward:
```
gosnmp currently only supports SNMP SETs for Integers, IPAddress and OctetStrings
```
In your fork the `Set` function is just
```
// Set sends an SNMP SET request
func (x *GoSNMP) Set(pdus []SnmpPDU) (result *SnmpPacket, err error) {
	var packetOut *SnmpPacket
	packetOut = x.mkSnmpPacket(SetRequest, pdus, 0, 0)
	return x.send(packetOut, true)
}
```
While `gosnmp/gosnmp` it is:
```
// Set sends an SNMP SET request
func (x *GoSNMP) Set(pdus []SnmpPDU) (result *SnmpPacket, err error) {
	var packetOut *SnmpPacket
	switch pdus[0].Type {
	// TODO test Gauge32
	case Integer, OctetString, Gauge32, IPAddress, ObjectIdentifier:
		packetOut = x.mkSnmpPacket(SetRequest, pdus, 0, 0)
	default:
		return nil, fmt.Errorf("ERR:gosnmp currently only supports SNMP SETs for Integers, IPAddress and OctetStrings")
	}
	return x.send(packetOut, true)
}
```

If we need to support Counter64 Set, then I'll work on getting a PR to `gosnmp/gosnmp`

**Comment by upsampled** [comment]
Tracking `TestServerTestsSuite/TestGetSetOids/SNMPSet/ByGoSNMP/Counter32`  issue in my bigger ticket gosnmp/gosnmp#448 

@slayercat if you could look at `TestServerTestsSuite/TestGetSetOids/SNMPWalk` that be great, if not I will get around to it eventually

**Comment by slayercat** [comment]
Thank you for your investigation. I apologize for the delayed response during this time due to personal matters.

I believe that as the upstream gosnmp library improves, the set issues can gradually be resolved. Additionally, some set operations lack use cases and packet captures, so I tend to ignore TestGetSetOids/SNMPSet.

On the other hand, in the previous commit (tag v0.4), the tests for TestGetSetOids/SNMPWalk were successful. Therefore, while this could possibly be caused by an existing issue, I would like to investigate to ensure that no other problems have been introduced.

I would greatly appreciate it if you could assist in the investigation. I expect to return to normal responsiveness by October 8th.

**Comment by upsampled** [comment]
@slayercat the issue is isolated to the `OpaqueFloat` type (see logs in #22 ). Not sure the specifics yet.

**Comment by upsampled** [comment]
The issue is that `OpaqueDouble` and `OpaqueFloat` are having issue when set to `0`

**Comment by upsampled** [comment]
Ok so far the outstanding times to get these tests working are all in `gosnmp`, the issues are:

* Handle `0.0` value for floats (currently in gosnmp/gosnmp#452)
* Counter32 Set Support (currently in gosnmp/gosnmp#452)
* Counter64 Set Support
* Null Set and Marshalling Support
* TimeTicks Support 
* Uinterger32 support

**Comment by upsampled** [comment]
Ok I have everything working on GoSNMPServer's side with just that additional change to hand IP Addresses.

I have the rest of the items above working locally for `gosnmp` but I just need to write tests and the them accepted in the PR

**Comment by upsampled** [comment]
Ok all needed changes are in gosnmp#452. If/When that is accepted all tests will pass.

**Comment by slayercat** [comment]
Thanks~ Merged.

**Pull request merged**
