### PR TITLE
bug:oidToByteString

### PR DESCRIPTION
**Pull request by ZaneXo**
1. When converting certain byte values ​​to the rune type, some byte values ​​may not be represented correctly because the rune type represents a Unicode character. This can cause byte values ​​to become unpredictable or incorrect after conversion.
2. Each time a new request is received, such as Get, Get-Next, it will perform multiple oidToByteString operations, there is additional cpu overhead，but this is not necessary.
3. If it is to verify the legitimacy of the OID, is it more appropriate to only perform the verification in SyncConfig, not when subsequent new requests flow in?

### CODE REVIEW

**Comment by slayercat** [comment]
It's so kind of you to help.

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Comment by ZaneXo** [comment]
Preparing review...

**Pull request merged**
